---
- name: Install composer
  shell:
    wget https://getcomposer.org/composer.phar && /bin/mv composer.phar /usr/local/bin/composer && chmod +x /usr/local/bin/composer

- name: Github token
  shell: cd /vagrant/app/src/ &&  sudo composer config github-oauth.github.com  0b453cf584e11728a6bf4dd832a94f050a395626

- name: Set fxp/composer-asset-plugin
  shell: sudo /usr/local/bin/composer global require --no-interaction  "fxp/composer-asset-plugin:1.0.0-beta3"